"""make max_qty nullable

Revision ID: 7547e9384479
Revises: 27c6b1536331
Create Date: 2025-08-11 19:08:35.372834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7547e9384479'
down_revision: Union[str, Sequence[str], None] = '27c6b1536331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'cost_per_unit_usd',
               existing_type=mysql.DECIMAL(precision=20, scale=8),
               type_=sa.DECIMAL(precision=23, scale=8),
               existing_nullable=False)
    op.alter_column('products', 'min_qty',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('products', 'max_qty',
               existing_type=mysql.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'max_qty',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('products', 'min_qty',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('products', 'cost_per_unit_usd',
               existing_type=sa.DECIMAL(precision=23, scale=8),
               type_=mysql.DECIMAL(precision=20, scale=8),
               existing_nullable=False)
    # ### end Alembic commands ###
